function [elementType,sectionType,mirrorType,compTwist] = beamPropertyOptions()
%% beamPropertyOptions
% 
% Available parameters - used with indices returned from
% St7GetBeamPropertyData
% 
% author: john devitis
% create date: 15-Aug-2016 15:26:09
	
    % beam element data options
    elementType = {'kBeamTypeNull' 'kBeamTypeSpring' 'kBeamTypeCable'...
                   'kBeamTypeTruss' 'kBeamTypeCutoff' 'kBeamTypeContact'...
                   'kBeamTypeBeam' 'kBeamTypeUser' 'kBeamTypePipe'...
                   'kBeamTypeConnection'};
    % beam section type options
    sectionType = {'kNullSection' 'kCircularSolid' 'kCircularHollow'...
                   'kSquareSolid' 'kSquareHollow' 'kLipChannel'...
                   'kTopHatChannel' 'kISection' 'kTSection' 'kLSection'... 
                   'kZSection' 'kUserSection' 'kTrapezoidSolid'...
                   'kTrapezoidHollow' 'kTriangleSolid' 'kTriangleHollow'...
                   'kCruciform'};
    % section mirror options
    mirrorType = {'kMirrorNone' 'kMirrorTop' 'kMirrorBot' 'kMirrorLeft' ...
                  'kMirrorRight' 'kMirrorLeftAndTop' 'kMirrorLeftAndBot' ...
                  'MirrorRightAndTop' 'kMirrorRightAndBot' ...
                  'kMirrorLeftTopOnly' 'kMirrorLeftBotOnly' ...
                  'kMirrorRightTopOnly' 'kMirrorRightBotOnly'};
    % compatible twist option for mirrored sections
    compTwist = {'btTrue','btFalse'};
	
	
end
